// -------- START USERS REQUESTS -------- //
### GET ALL USERS
GET http://localhost:8000/api/users
Content-Type: application/json

### REGISTER A USER
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
  "name": "Rao Akif 02",
  "username": "raoakif02",
  "email": "akifrao02@gmail.com",
  "password": "123456"
}

### LOGIN USER
POST http://localhost:8000/api/auth/
Content-Type: application/json

{
  "pseudonym": "raoakif",
  "password": "123456"
}

### GET ALL USERS
GET http://localhost:8000/api/users
Content-Type: application/json

### GET USER BY ID
GET http://localhost:8000/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### EDIT USER
PUT http://localhost:8000/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
    "pseudonym": "raoakif",
    "email": "akifrao@gmail.com",
    "password": "123456",
    "profileImage": "https://raw.githubusercontent.com/Immages/writinghat/main/caps/thinking_cap1.png"
}

### DELETE A USER
DELETE http://localhost:8000/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA
// -------- END USERS REQUESTS -------- //

# ---------------------------------------------------------

// -------- START PROMPT-CATEGORY REQUESTS -------- //
### ADD A PROMT-CATEGORY



### REGISTER A USER
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "name": "Rao Akif 01",
  "pseudonym": "raoakif01",
  "email": "akifrao01@gmail.com",
  "password": "123456"
}