// -------- START COACHES REQUESTS -------- //
### GET ALL COACHES
GET http://localhost:5000/api/coaches
Content-Type: application/json

### REGISTER A COACH
POST http://localhost:5000/api/coaches/register
Content-Type: application/json

{
  "name": "Coach 01",
  "username": "coach01",
  "email": "coach01@gmail.com",
  "password": "123456"
}

### LOGIN COACH
POST http://localhost:5000/api/auth/coach/login
Content-Type: application/json

{
  "username": "coach01",
  "password": "123456"
}

### LOGIN PLAYER
POST http://localhost:5000/api/auth/player/login
Content-Type: application/json

{
  "username": "johndoe",
  "password": "7J$11^xA"
}

### GET ALL COACHES
GET http://localhost:5000/api/coaches
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4Njc0MjAwNCwiZXhwIjoxNjg3MzQ2ODA0fQ.a-eL0aEWxY0qWOqyGZ8PKst9nAwxU7XeytJ1-hMXvEs

### GET COACH BY ID
GET http://localhost:5000/api/coaches/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4Njc0MjAwNCwiZXhwIjoxNjg3MzQ2ODA0fQ.a-eL0aEWxY0qWOqyGZ8PKst9nAwxU7XeytJ1-hMXvEs

### EDIT COACH
PUT http://localhost:5000/api/coaches/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4Njc0MjAwNCwiZXhwIjoxNjg3MzQ2ODA0fQ.a-eL0aEWxY0qWOqyGZ8PKst9nAwxU7XeytJ1-hMXvEs

{
  "name": "Coach 01",
  "username": "coach01",
  "email": "coach01@gmail.com",
  "password": "123456"
}

### DELETE A COACH
DELETE http://localhost:5000/api/coaches/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4Njc0MjAwNCwiZXhwIjoxNjg3MzQ2ODA0fQ.a-eL0aEWxY0qWOqyGZ8PKst9nAwxU7XeytJ1-hMXvEs
// -------- END COACHES REQUESTS -------- //

# ---------------------------------------------------------

// -------- START PLAYER REQUESTS -------- //

### Create a new Player
POST http://localhost:5000/api/players
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MSwidXNlcm5hbWUiOiJjb2FjaDAxIn0sImlhdCI6MTY5MjY5MjU2MSwiZXhwIjoxNjkzMjk3MzYxfQ.e_T_69pfGo1xIR3GdLcGyfWAb3h_FoL7chB1EtEm3oE

# {
#   "name": "John Doe",
#   "username": "johndoe",
#   "email": "johndoe@gmail.com",
#   "number": "+923330508717",
#   "position": "GOAL_KEEPER",
#   "availability_status": "PENDING"
# }

{
  "name": "Jenny Doe2",
  "username": "jennydoe2",
  "email": "jennydoe2@gmail.com",
  "number": "+923330508717",
  "position": "FULL_BACK_RIGHT",
  "availability_status": "PENDING"
}


### Get all players
GET http://localhost:5000/api/players
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MSwidXNlcm5hbWUiOiJjb2FjaDAxIn0sImlhdCI6MTY5MjY5MjU2MSwiZXhwIjoxNjkzMjk3MzYxfQ.e_T_69pfGo1xIR3GdLcGyfWAb3h_FoL7chB1EtEm3oE

### Get a player by ID
GET http://localhost:5000/api/players/:id

### Update a player
PUT http://localhost:5000/api/players/:id
Content-Type: application/json

{
  {
  "name": "Jenny Doe",
  "number": "+923216363147"
}
}

### Delete a player
DELETE http://localhost:5000/api/players/:id

// -------- END PLAYER REQUESTS -------- //

# ---------------------------------------------------------

// -------- START TEAM REQUESTS -------- //

### Create a new Team
POST http://localhost:5000/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4Njc0MjAwNCwiZXhwIjoxNjg3MzQ2ODA0fQ.a-eL0aEWxY0qWOqyGZ8PKst9nAwxU7XeytJ1-hMXvEs

{
  "name": "Team 01",
  "playerIds": [1, 2]
}

### Get all teams
GET http://localhost:5000/api/teams



### Get a team by ID
GET http://localhost:5000/api/teams/:id



### Update a team
PUT http://localhost:5000/api/teams/:id
Content-Type: application/json

{
  "playerIds": [3, 4]
}


### Delete a team
DELETE http://localhost:5000/api/teams/:id


### Get all players in a team
# GET http://localhost:5000/api/teams/:id/players
GET http://localhost:5000/api/teams/1/players


// -------- END TEAM REQUESTS -------- //

# ---------------------------------------------------------

// -------- START EVENT REQUESTS -------- //

### Create a new Event
POST http://localhost:5000/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4Njc0MjAwNCwiZXhwIjoxNjg3MzQ2ODA0fQ.a-eL0aEWxY0qWOqyGZ8PKst9nAwxU7XeytJ1-hMXvEs

{
  "title": "Final Match",
  "event_type": "MATCH",
  "date": "2023-06-10",
  "time": "15:00",
  "location": "Stadium XYZ",
  "details": "Important match against Team ABC",
  "teamId": 1
}

### Get all events
GET http://localhost:5000/api/events

### Get an event by ID
GET http://localhost:5000/api/events/1

### Update an event
PUT http://localhost:5000/api/events/:id
Content-Type: application/json

{
  "title": "Final Match",
  "event_type": "PRACTICE",
  "date": "2023-06-12",
  "time": "10:00",
  "location": "Training Ground",
  "details": "Practice session for upcoming match",
  "teamId": 1
}

### Delete an event
DELETE http://localhost:5000/api/events/:id

### Get an event with all players
GET http://localhost:5000/api/events/1/players


# GET http://localhost:5000/api/events/:id/players/:playerId/availability

### Update the availability status of players in an event
PUT http://localhost:5000/api/events/1/players/1/availability
Content-Type: application/json

{
  "availability_status": "GOING"
}


# POST http://localhost:5000/api/events/:eventId/generate-invitation
### Get an event with all players
POST http://localhost:5000/api/events/1/generate-invitation

// -------- END EVENT REQUESTS -------- //
