// -------- START COACHES REQUESTS -------- //
### GET ALL COACHES
GET http://localhost:8000/api/coaches
Content-Type: application/json

### REGISTER A USER
POST http://localhost:8000/api/coaches/register
Content-Type: application/json

{
  "name": "Coach 01",
  "username": "coach01",
  "email": "coach01@gmail.com",
  "password": "123456"
}

### LOGIN USER
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "username": "coach01",
  "password": "123456"
}

### GET ALL COACHES
GET http://localhost:8000/api/coaches
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4NjczMTQ5MiwiZXhwIjoxNjg3MzM2MjkyfQ.uTj3twqCYEkWP7K3Uhr7bGqptMGWnXjPlI2M6ihkQq0

### GET USER BY ID
GET http://localhost:8000/api/coaches/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4NjczMTQ5MiwiZXhwIjoxNjg3MzM2MjkyfQ.uTj3twqCYEkWP7K3Uhr7bGqptMGWnXjPlI2M6ihkQq0

### EDIT USER
PUT http://localhost:8000/api/coaches/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4NjczMTQ5MiwiZXhwIjoxNjg3MzM2MjkyfQ.uTj3twqCYEkWP7K3Uhr7bGqptMGWnXjPlI2M6ihkQq0

{
    "pseudonym": "raoakif",
    "email": "akifrao@gmail.com",
    "password": "123456",
    "profileImage": "https://raw.githubusercontent.com/Immages/writinghat/main/caps/thinking_cap1.png"
}

### DELETE A USER
DELETE http://localhost:8000/api/coaches/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDb2FjaEluZm8iOnsiY29hY2hJZCI6MX0sImlhdCI6MTY4NjczMTQ5MiwiZXhwIjoxNjg3MzM2MjkyfQ.uTj3twqCYEkWP7K3Uhr7bGqptMGWnXjPlI2M6ihkQq0
// -------- END COACHES REQUESTS -------- //

# ---------------------------------------------------------

// -------- START PROMPT-CATEGORY REQUESTS -------- //
### ADD A PROMT-CATEGORY



### REGISTER A USER
POST http://localhost:8000/api/coaches
Content-Type: application/json

{
  "name": "Rao Akif 01",
  "pseudonym": "raoakif01",
  "email": "akifrao01@gmail.com",
  "password": "123456"
}