// -------- START USERS REQUESTS -------- //
### GET ALL USERS
GET https://smart-coach-api.vercel.app/api/users
Content-Type: application/json

### REGISTER A USER
POST https://smart-coach-api.vercel.app/api/auth/register
Content-Type: application/json

{
  "name": "Rao Akif 03",
  "pseudonym": "raoakif03",
  "email": "akifrao03@gmail.com",
  "password": "123456"
}

### LOGIN USER
POST https://smart-coach-api.vercel.app/api/auth/
Content-Type: application/json

{
  "pseudonym": "raoakif",
  "password": "123456"
}

### GET ALL USERS
GET https://smart-coach-api.vercel.app/api/users
Content-Type: application/json

### GET USER BY ID
GET https://smart-coach-api.vercel.app/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

### EDIT USER
PUT https://smart-coach-api.vercel.app/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA

{
    "pseudonym": "raoakif",
    "email": "akifrao@gmail.com",
    "password": "123456",
    "profileImage": "https://raw.githubusercontent.com/Immages/writinghat/main/caps/thinking_cap1.png"
}

### DELETE A USER
DELETE https://smart-coach-api.vercel.app/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJwc2V1ZG9ueW0iOiJyYW9ha2lmIn0sImlhdCI6MTY4MjYzMTc4MiwiZXhwIjoxNjgzMjM2NTgyfQ.ucJTIgrHYIUHIEosirCyzu6YrDhodqllheG5u8ws6FA
// -------- END USERS REQUESTS -------- //

# ---------------------------------------------------------

// -------- START ROSTER REQUESTS -------- //

### Create a new Roster
POST https://smart-coach-api.vercel.app/api/rosters
Content-Type: application/json

{
  "playerIds": [1, 2]
}


### Get all rosters
GET https://smart-coach-api.vercel.app/api/rosters



### Get a roster by ID
GET https://smart-coach-api.vercel.app/api/rosters/:id



### Update a roster
PUT https://smart-coach-api.vercel.app/api/rosters/:id
Content-Type: application/json

{
  "playerIds": [3, 4]
}


### Delete a roster
DELETE https://smart-coach-api.vercel.app/api/rosters/:id


### Get all players in a roster
# GET https://smart-coach-api.vercel.app/api/rosters/:id/players
GET https://smart-coach-api.vercel.app/api/rosters/1/players


// -------- END ROSTER REQUESTS -------- //